name: sr_hub
description: Study Resource Hub - A comprehensive platform for managing study resources, book reservations, and seat bookings.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Firebase - Using compatible versions to avoid type casting issues
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Navigation
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.6

  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1

  # Animations
  lottie: ^2.7.0

  # HTTP requests (if needed)
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets if you have any
  # assets:
  #   - images/
  #   - icons/

  # Add fonts if you have any
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf